global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dotnet-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5180']

  - job_name: 'jaeger'
    metrics_path: /metrics
