_format_version: "2.1"
services:
  - name: sua-api
    url: http://api:5000
    routes:
      - name: minha-rota
        paths:
          - /
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: true
