global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:5000']
  
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
